#!/bin/bash

#netfile="\"DQN3_0_1_breakout_FULL_Y.t7\""
#update_freq=4
#agent_params="ep="$eps_start",ep_end="$eps_end",ep_endt="$eps_endt",lr="$lr",lr_end="$lr_end",lr_endt="$lr_endt",wc="$wc",discount="$discount",hist_len=4,learn_start="$learn_start",replay_memory="$replay_memory",update_freq="$update_freq",n_replay="$n_replay",network="$netfile",preproc="$preproc_net",state_dim="$state_dim",minibatch_size=32,rescale_r=1,ncols="$ncols",bufferSize=512,valid_size=500,target_q=10000,clip_delta=1,min_reward=-1,max_reward=1"
#args="-framework $FRAMEWORK -game_path $game_path -name $agent_name -env $ENV -env_params $env_params -agent $agent -agent_params $agent_params -steps $steps -eval_freq $eval_freq -eval_steps $eval_steps -prog_freq $prog_freq -save_freq $save_freq -actrep $actrep -gpu $gpu -random_starts $random_starts -pool_frms $pool_frms -seed $seed -threads $num_threads"
#echo $args
#../torch/bin/qlua train_agent.lua $args

logNum=0
log='log'
txt='.txt'
for deepOut in 1 0
do
for deepOutNonLin in 'none' 'relu' 'sigm' 'tanh' 
do
for batch_norm in 0 1 
do
for deepOutDropout in 0.5 0.2
do

let "logNum=logNum+1"
echo "th main.lua -savefile word-small -word_vec_size 200 -highway_layers 0 -use_chars 0 -use_words 1 -rnn_size 200 -gpuid 0 -cudnn 1 -data_dir data/5mb_dArt/ -batch_norm $batch_norm -deepOut $deepOut -deepOutdim '{200,400}' -deepOutNonLin $deepOutNonLin -deepOutDropout $deepOutDropout -weight_decay 1.0 -learning_rate_decay 0.997 -logFile $log$logNum$txt -max_epochs 1 -ignoreTestSet 1"
th main.lua -savefile word-small -word_vec_size 200 -highway_layers 0 -use_chars 0 -use_words 1 -rnn_size 200 -gpuid 0 -cudnn 1 -data_dir data/5mb_dArt/ -batch_norm $batch_norm -deepOut $deepOut -deepOutdim '{200,400}' -deepOutNonLin $deepOutNonLin -deepOutDropout $deepOutDropout -weight_decay 1.0 -learning_rate_decay 0.997 -logFile $log$logNum$txt -max_epochs 1 -ignoreTestSet 1

done # for deepOutDropout in 0.5 0.2
done # for batch_norm in 0 1 
done # for deepOutNonLin in 'relu' 'sigm' 'tanh' 'none'
done # for deepOut in 0 1